apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-service
  namespace: springofficehours-io
spec:
  template:
    spec:
      containers:
        - image: dashaun/io.springofficehours.service.image:latest