apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: image-service
  namespace: springofficehours-io
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/initial-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: dashaun/io.springofficehours.service.image:v0.0.22-x86_64
